name: Manual Headless Selenium Run

on:
  workflow_dispatch:  # Trigger manually

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Chrome & ChromeDriver
        run: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install -y ./google-chrome-stable_current_amd64.deb
            CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+\.\d+")
            CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r --arg v "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
            wget -O chromedriver.zip "$CHROMEDRIVER_VERSION"
            unzip chromedriver.zip
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq unzip
          python -m pip install --upgrade pip
          pip install requests selenium

      - name: Check if within allowed hours
        id: check_time
        run: |
          # Define time ranges (US Eastern Time)
          current_hour=$(TZ="America/New_York" date +%H)
          if [[ "$current_hour" -ge 8 && "$current_hour" -lt 12 ]] || \
             [[ "$current_hour" -ge 13 && "$current_hour" -lt 17 ]] || \
             [[ "$current_hour" -ge 18 && "$current_hour" -lt 23 ]] || \
             [[ "$current_hour" -ge 0 && "$current_hour" -lt 2 ]]; then
            echo "Within allowed time range."
            echo "::set-output name=proceed::true"
          else
            echo "Outside allowed time range. Pausing execution."
            echo "::set-output name=proceed::false"
          fi

      - name: Run user scripts
        if: steps.check_time.outputs.proceed == 'true'
        run: |
          # Run the user's script based on passed argument
          USER_FOLDERS=("Alex" "Alice" "Bob" "Brandon" "Christo" "Cristina" "Derek" "Georgiana" "Lexie" "Mark" "Marly" "Molly" "Neutral")
          for USER in "${USER_FOLDERS[@]}"; do
            echo "Running script for $USER"
            cd ${{ github.workspace }}/$USER  # Navigate to the user-specific folder
            chmod +x run_profile.sh
            ./run_profile.sh /path/to/batches  # Adjust the batch path if necessary
          done

    