name: Manual Headless Selenium Run

on:
  workflow_dispatch:  # Trigger manually

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chromium & ChromeDriver
        run: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser chromium-chromedriver
            sudo ln -sf /usr/bin/chromedriver /usr/local/bin/chromedriver
            if [ ! -f /usr/bin/google-chrome ]; then
              sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
            fi
        

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium script
        run: python profile_setup.py
