name: Manual Headless Selenium Run

on:
  workflow_dispatch:  # Trigger manually

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Chrome & ChromeDriver
        run: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install -y ./google-chrome-stable_current_amd64.deb
            CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+\.\d+")
            CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r --arg v "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
            wget -O chromedriver.zip "$CHROMEDRIVER_VERSION"
            unzip chromedriver.zip
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
        

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq unzip
          python -m pip install --upgrade pip
          pip install requests selenium

      - name: Run Selenium script
        run: python profile_setup.py

      - name: Upload error screenshot
        if: failure()  # This condition ensures the artifact is uploaded only if the script fails
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error.png
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: google-location-screenshot
          path: | 
            e1.png
            e2.png
            e3.png
            e4.png
            e5.png
            e6.png
            e7.png
            e8.png

      
